# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Ops
    

      class GetTransactionByIdV1TransactionsTransactionIdGetRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier of the transaction to retrieve.
        field :transaction_id, ::String, { 'path_param': { 'field_name': 'transaction_id', 'style': 'simple', 'explode': false } }

        sig { params(transaction_id: ::String).void }
        def initialize(transaction_id:)
          @transaction_id = transaction_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @transaction_id == other.transaction_id
          true
        end
      end
    end
  end
end
