# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Ops
    

      class GetExemptionByIdV1ExemptionsExemptionIdGetRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier for the exemption being retrieved.
        field :exemption_id, ::String, { 'path_param': { 'field_name': 'exemption_id', 'style': 'simple', 'explode': false } }

        sig { params(exemption_id: ::String).void }
        def initialize(exemption_id:)
          @exemption_id = exemption_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @exemption_id == other.exemption_id
          true
        end
      end
    end
  end
end
