# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Ops
    

      class GetTransactionByExternalIdRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique external identifier of the transaction.
        field :external_id, ::String, { 'path_param': { 'field_name': 'external_id', 'style': 'simple', 'explode': false } }

        sig { params(external_id: ::String).void }
        def initialize(external_id:)
          @external_id = external_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @external_id == other.external_id
          true
        end
      end
    end
  end
end
