# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Ops

      class SuggestionsV1AddressValidationSuggestionsPostRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :validation_address, Models::Shared::ValidationAddress, { 'request': { 'media_type': 'application/json' } }
        # The unique identifier for the organization making the request
        field :x_organization_id, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'x-organization-id', 'style': 'simple', 'explode': false } }

        sig { params(validation_address: Models::Shared::ValidationAddress, x_organization_id: T.nilable(::String)).void }
        def initialize(validation_address:, x_organization_id: nil)
          @validation_address = validation_address
          @x_organization_id = x_organization_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @validation_address == other.validation_address
          return false unless @x_organization_id == other.x_organization_id
          true
        end
      end
    end
  end
end
