# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class AddressType < T::Enum


        enums do
          BILL_TO = new('BILL_TO')
          SHIP_TO = new('SHIP_TO')
          SHIP_FROM = new('SHIP_FROM')
          BILL_FROM = new('BILL_FROM')
        end
      end
    end
  end
end
