# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class AddressSearchResponse
        extend T::Sig
        include Crystalline::MetadataFields


        field :address_submitted, Models::Shared::AddressSubmittedResponse, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('address_submitted'), required: true } }

        field :response_address, Models::Shared::AddressResponseData, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('response_address'), required: true } }
        # Indicates if the address was VERIFIED, PARTIALLY_VERIFIED, INVALID, UNVERIFIABLE, BLANK
        field :verification_status, ::String, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('verification_status'), required: true } }
        # List of additional fields added to enrich the address
        field :enrich_fields, Crystalline::Array.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('enrich_fields'), required: true } }

        sig { params(address_submitted: Models::Shared::AddressSubmittedResponse, response_address: Models::Shared::AddressResponseData, verification_status: ::String, enrich_fields: T::Array[::String]).void }
        def initialize(address_submitted:, response_address:, verification_status:, enrich_fields:)
          @address_submitted = address_submitted
          @response_address = response_address
          @verification_status = verification_status
          @enrich_fields = enrich_fields
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @address_submitted == other.address_submitted
          return false unless @response_address == other.response_address
          return false unless @verification_status == other.verification_status
          return false unless @enrich_fields == other.enrich_fields
          true
        end
      end
    end
  end
end
