# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class AppliedTo < T::Enum


        enums do
          TRANSACTION = new('TRANSACTION')
          TRANSACTION_ITEM = new('TRANSACTION_ITEM')
        end
      end
    end
  end
end
