# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class BackendSrcExemptionsSerializersExemptionRead
        extend T::Sig
        include Crystalline::MetadataFields

        # Start date for the exemption validity period (YYYY-MM-DD format)
        field :start_date, ::Date, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('start_date'), required: true, 'decoder': Utils.date_from_iso_format(false) } }
        # Unique identifier for the exemption
        field :id, ::String, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('id'), required: true } }

        field :exemption_type, Models::Shared::ExemptionType, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('exemption_type'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::ExemptionType, false) } }

        field :status, Models::Shared::ExemptionStatus, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::ExemptionStatus, false) } }

        field :country_code, Crystalline::Nilable.new(Models::Shared::CountryCodeEnum), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('country_code'), 'decoder': Utils.enum_from_string(Models::Shared::CountryCodeEnum, true) } }
        # The jurisdiction identifier for the exemption
        field :jurisdiction, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('jurisdiction') } }
        # End date for the exemption validity period (YYYY-MM-DD format)
        field :end_date, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('end_date') } }
        # Unique identifier for the transaction, if applicable
        field :transaction_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('transaction_id') } }
        # Federal Employer Identification Number
        field :fein, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('FEIN') } }
        # Sales tax ID for the exemption
        field :sales_tax_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('sales_tax_id') } }

        field :customer, Crystalline::Nilable.new(Models::Shared::CustomerRead), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('customer') } }
        # List of attachments related to the exemption
        field :attachment, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::AttachmentRead)), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('attachment') } }
        # Indicates whether the exemption is for a reseller
        field :reseller, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('reseller') } }

        sig { params(start_date: ::Date, id: ::String, exemption_type: Models::Shared::ExemptionType, status: Models::Shared::ExemptionStatus, country_code: T.nilable(Models::Shared::CountryCodeEnum), jurisdiction: T.nilable(::String), end_date: T.nilable(::String), transaction_id: T.nilable(::String), fein: T.nilable(::String), sales_tax_id: T.nilable(::String), customer: T.nilable(Models::Shared::CustomerRead), attachment: T.nilable(T::Array[Models::Shared::AttachmentRead]), reseller: T.nilable(T::Boolean)).void }
        def initialize(start_date:, id:, exemption_type:, status:, country_code: nil, jurisdiction: nil, end_date: nil, transaction_id: nil, fein: nil, sales_tax_id: nil, customer: nil, attachment: nil, reseller: false)
          @start_date = start_date
          @id = id
          @exemption_type = exemption_type
          @status = status
          @country_code = country_code
          @jurisdiction = jurisdiction
          @end_date = end_date
          @transaction_id = transaction_id
          @fein = fein
          @sales_tax_id = sales_tax_id
          @customer = customer
          @attachment = attachment
          @reseller = reseller
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @start_date == other.start_date
          return false unless @id == other.id
          return false unless @exemption_type == other.exemption_type
          return false unless @status == other.status
          return false unless @country_code == other.country_code
          return false unless @jurisdiction == other.jurisdiction
          return false unless @end_date == other.end_date
          return false unless @transaction_id == other.transaction_id
          return false unless @fein == other.fein
          return false unless @sales_tax_id == other.sales_tax_id
          return false unless @customer == other.customer
          return false unless @attachment == other.attachment
          return false unless @reseller == other.reseller
          true
        end
      end
    end
  end
end
