# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared

      class DocumentTypeEnum < T::Enum
        enums do
          INVOICE = new('INVOICE')
          SALES_ORDER = new('SALES_ORDER')
        end
      end
    end
  end
end
