# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class ExemptionType < T::Enum


        enums do
          CUSTOMER = new('customer')
          WHOLESALE = new('wholesale')
          TRANSACTION = new('transaction')
        end
      end
    end
  end
end
