# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared

      class FindThresholdCrossingTransactionState
        extend T::Sig
        include Crystalline::MetadataFields


        field :period_start_date, ::String, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('period_start_date'), required: true } }

        field :period_end_date, ::String, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('period_end_date'), required: true } }

        field :running_sales_total_decimal, ::String, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('running_sales_total_decimal'), required: true } }

        field :running_transaction_count, ::Integer, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('running_transaction_count'), required: true } }

        field :has_all_marketplace_transactions, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('has_all_marketplace_transactions'), required: true } }

        field :last_txn_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('last_txn_id') } }

        field :last_txn_datetime, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('last_txn_datetime') } }

        sig { params(period_start_date: ::String, period_end_date: ::String, running_sales_total_decimal: ::String, running_transaction_count: ::Integer, has_all_marketplace_transactions: T::Boolean, last_txn_id: T.nilable(::String), last_txn_datetime: T.nilable(::String)).void }
        def initialize(period_start_date:, period_end_date:, running_sales_total_decimal:, running_transaction_count:, has_all_marketplace_transactions:, last_txn_id: nil, last_txn_datetime: nil)
          @period_start_date = period_start_date
          @period_end_date = period_end_date
          @running_sales_total_decimal = running_sales_total_decimal
          @running_transaction_count = running_transaction_count
          @has_all_marketplace_transactions = has_all_marketplace_transactions
          @last_txn_id = last_txn_id
          @last_txn_datetime = last_txn_datetime
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @period_start_date == other.period_start_date
          return false unless @period_end_date == other.period_end_date
          return false unless @running_sales_total_decimal == other.running_sales_total_decimal
          return false unless @running_transaction_count == other.running_transaction_count
          return false unless @has_all_marketplace_transactions == other.has_all_marketplace_transactions
          return false unless @last_txn_id == other.last_txn_id
          return false unless @last_txn_datetime == other.last_txn_datetime
          true
        end
      end
    end
  end
end
