# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class NexusStateEnum < T::Enum


        enums do
          EXPOSED = new('EXPOSED')
          APPROACHING = new('APPROACHING')
          PENDING_REGISTRATION = new('PENDING_REGISTRATION')
          OSS_PENDING_REGISTRATION = new('OSS_PENDING_REGISTRATION')
          REGISTERED = new('REGISTERED')
          OSS_REGISTERED = new('OSS_REGISTERED')
          NOT_EXPOSED = new('NOT_EXPOSED')
        end
      end
    end
  end
end
