# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class ProductCategories
        extend T::Sig
        include Crystalline::MetadataFields

        # Name of the product category
        #             (e.g., PHYSICAL, SERVICE, DIGITAL, MISCELLANEOUS)
        field :name, ::String, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('name'), required: true } }
        # List of subcategories associated with the product category
        field :subcategories, Crystalline::Array.new(Models::Shared::ProductSubCategory), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('subcategories'), required: true } }

        sig { params(name: ::String, subcategories: T::Array[Models::Shared::ProductSubCategory]).void }
        def initialize(name:, subcategories:)
          @name = name
          @subcategories = subcategories
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @subcategories == other.subcategories
          true
        end
      end
    end
  end
end
