# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class ProductCategoryEnum < T::Enum


        enums do
          PHYSICAL = new('PHYSICAL')
          DIGITAL = new('DIGITAL')
          SERVICE = new('SERVICE')
          UNKNOWN = new('UNKNOWN')
          MISCELLANEOUS = new('MISCELLANEOUS')
        end
      end
    end
  end
end
