# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class RegistrationsRegimeEnum < T::Enum


        enums do
          STANDARD = new('STANDARD')
          SIMPLIFIED = new('SIMPLIFIED')
        end
      end
    end
  end
end
