# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class RelatedEntityType < T::Enum


        enums do
          EXEMPTION = new('EXEMPTION')
          REGISTRATION = new('REGISTRATION')
          FILING = new('FILING')
          FILING_PAYMENT = new('FILING_PAYMENT')
        end
      end
    end
  end
end
