# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared

      class SourceEnum < T::Enum
        enums do
          BIGCOMMERCE = new('BIGCOMMERCE')
          BESTBUY = new('BESTBUY')
          BUNNY = new('BUNNY')
          CHARGEBEE = new('CHARGEBEE')
          SHOPIFY = new('SHOPIFY')
          STRIPE = new('STRIPE')
          AMAZON = new('AMAZON')
          TIKTOK = new('TIKTOK')
          CUSTOM = new('CUSTOM')
          UNKNOWN = new('UNKNOWN')
          IMPORT = new('IMPORT')
          ZUORA = new('ZUORA')
          APIDECK = new('APIDECK')
          QUICKBOOKS = new('QUICKBOOKS')
          API = new('API')
          APPLE_APP_STORE = new('APPLE_APP_STORE')
          GOOGLE_APP_STORE = new('GOOGLE_APP_STORE')
          WALMART = new('WALMART')
          PAYPAL = new('PAYPAL')
          NETSUITE = new('NETSUITE')
          XERO = new('XERO')
          MAXIO = new('MAXIO')
          RECURLY = new('RECURLY')
          SALESFORCE = new('SALESFORCE')
          ETSY = new('ETSY')
          EBAY = new('EBAY')
          WIX = new('WIX')
          SQUARESPACE = new('SQUARESPACE')
          WOOCOMMERCE = new('WOOCOMMERCE')
          MAGENTO = new('MAGENTO')
          BILLING_PLATFORM = new('BILLING_PLATFORM')
          DEEL = new('DEEL')
          RIPPLING = new('RIPPLING')
          GUSTO = new('GUSTO')
          FACEBOOK = new('FACEBOOK')
          OTHER = new('OTHER')
          ORDWAY = new('ORDWAY')
          INSTAGRAM = new('INSTAGRAM')
          PINTEREST = new('PINTEREST')
          WAYFAIR = new('WAYFAIR')
          WISH = new('WISH')
          POS = new('POS')
          TARGET = new('TARGET')
          NEWEGG = new('NEWEGG')
          GROUPON = new('GROUPON')
          GOOGLE_EXPRESS = new('GOOGLE_EXPRESS')
          NOCNOC = new('NOCNOC')
          MERCADO_LIBRE = new('MERCADO_LIBRE')
          MODALYST = new('MODALYST')
          NORDSTROM = new('NORDSTROM')
          FAIRE = new('FAIRE')
          SHOPWARE = new('SHOPWARE')
          ZOHO = new('ZOHO')
          SAGE_INTACCT = new('SAGE-INTACCT')
          AIRWALLEX = new('AIRWALLEX')
          ORB = new('ORB')
          ZENSKAR = new('ZENSKAR')
          MICROSOFT_DYNAMICS_365 = new('MICROSOFT_DYNAMICS_365')
          KICKSTARTER = new('KICKSTARTER')
          INTERNAL_ERP = new('INTERNAL_ERP')
        end
      end
    end
  end
end
