# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    
      # TaxExemptionEnum - This enum is used to determine if a transaction is exempt from tax.
      class TaxExemptionEnum < T::Enum


        enums do
          PRODUCT = new('PRODUCT')
          TRANSACTION = new('TRANSACTION')
          CUSTOMER = new('CUSTOMER')
          REGION = new('REGION')
          REVERSE_CHARGE = new('REVERSE_CHARGE')
          ZERO_RATE_TAX = new('ZERO_RATE_TAX')
          HIGH_VALUE_PHYSICAL_GOODS = new('HIGH_VALUE_PHYSICAL_GOODS')
          EXPORT = new('EXPORT')
          ZERO_VALUE_ITEM = new('ZERO_VALUE_ITEM')
          NO_RULE_FOUND = new('NO_RULE_FOUND')
          IMPORTED = new('IMPORTED')
        end
      end
    end
  end
end
