# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class TransactionStatusEnum < T::Enum


        enums do
          PENDING = new('PENDING')
          COMMITTED = new('COMMITTED')
          CANCELLED = new('CANCELLED')
          FULLY_REFUNDED = new('FULLY_REFUNDED')
          PARTIALLY_REFUNDED = new('PARTIALLY_REFUNDED')
          INVALID = new('INVALID')
          ARCHIVED = new('ARCHIVED')
        end
      end
    end
  end
end
