# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    
      # TransactionRefundStatus - Shopify has 2 order statuses for refund case: refunded and partially_refunded
      # If the given order has different status from these 2, we will set the
      # transaction's refund_status to PARTIALLY_REFUNDED by default.
      class TransactionRefundStatus < T::Enum


        enums do
          FULLY_REFUNDED = new('FULLY_REFUNDED')
          PARTIALLY_REFUNDED = new('PARTIALLY_REFUNDED')
        end
      end
    end
  end
end
