# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class TransactionItemBuilder
        extend T::Sig
        include Crystalline::MetadataFields

        # Organization identifier.
        field :organization_id, ::String, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('organization_id'), required: true } }
        # Date/time of item.
        field :date, ::DateTime, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('date'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }
        # External product identifier.
        field :external_product_id, ::String, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('external_product_id'), required: true } }
        # External item identifier.
        field :external_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('external_id') } }
        # Item description
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('description') } }
        # Product name
        field :product, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('product') } }
        # Product identifier.
        field :product_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('product_id') } }
        # Product name (detailed)
        field :product_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('product_name') } }
        # Product description
        field :product_description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('product_description') } }

        field :original_currency, Crystalline::Nilable.new(Models::Shared::CurrencyEnum), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('original_currency'), 'decoder': Utils.enum_from_string(Models::Shared::CurrencyEnum, true) } }

        field :destination_currency, Crystalline::Nilable.new(Models::Shared::CurrencyEnum), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('destination_currency'), 'decoder': Utils.enum_from_string(Models::Shared::CurrencyEnum, true) } }
        # Converted item amount.
        field :converted_amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('converted_amount') } }
        # Converted taxable amount.
        field :converted_taxable_amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('converted_taxable_amount') } }
        # Converted imported tax amount.
        field :converted_tax_amount_imported, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('converted_tax_amount_imported') } }
        # Converted calculated tax amount
        field :converted_tax_amount_calculated, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('converted_tax_amount_calculated') } }
        # Converted total discount amount.
        field :converted_total_discount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('converted_total_discount') } }
        # Converted subtotal amount.
        field :converted_subtotal, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('converted_subtotal') } }
        # This enum is used to determine if a transaction is exempt from tax.
        field :tax_exemption, Crystalline::Nilable.new(Models::Shared::TaxExemptionEnum), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('tax_exemption'), 'decoder': Utils.enum_from_string(Models::Shared::TaxExemptionEnum, true) } }

        field :tax_items, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::TaxItemBuilder)), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('tax_items') } }

        field :discount_builder, Crystalline::Nilable.new(Models::Shared::DiscountBuilder), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('discount_builder') } }
        # Quantity of item.
        field :quantity, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('quantity') } }
        # Item amount.
        field :amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('amount') } }
        # Imported tax amount for the item.
        field :tax_amount_imported, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('tax_amount_imported') } }
        # Imported tax rate.
        field :tax_rate_imported, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('tax_rate_imported') } }
        # Calculated tax amount for the item.
        field :tax_amount_calculated, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('tax_amount_calculated') } }
        # Calculated tax rate.
        field :tax_rate_calculated, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('tax_rate_calculated') } }
        # Taxable amount for the item.
        field :taxable_amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('taxable_amount') } }
        # Indicates if the item is exempt.
        field :exempt, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('exempt') } }

        sig { params(organization_id: ::String, date: ::DateTime, external_product_id: ::String, external_id: T.nilable(::String), description: T.nilable(::String), product: T.nilable(::String), product_id: T.nilable(::String), product_name: T.nilable(::String), product_description: T.nilable(::String), original_currency: T.nilable(Models::Shared::CurrencyEnum), destination_currency: T.nilable(Models::Shared::CurrencyEnum), converted_amount: T.nilable(::Float), converted_taxable_amount: T.nilable(::Float), converted_tax_amount_imported: T.nilable(::Float), converted_tax_amount_calculated: T.nilable(::Float), converted_total_discount: T.nilable(::Float), converted_subtotal: T.nilable(::Float), tax_exemption: T.nilable(Models::Shared::TaxExemptionEnum), tax_items: T.nilable(T::Array[Models::Shared::TaxItemBuilder]), discount_builder: T.nilable(Models::Shared::DiscountBuilder), quantity: T.nilable(::Float), amount: T.nilable(::Float), tax_amount_imported: T.nilable(::Float), tax_rate_imported: T.nilable(::Float), tax_amount_calculated: T.nilable(::Float), tax_rate_calculated: T.nilable(::Float), taxable_amount: T.nilable(::Float), exempt: T.nilable(T::Boolean)).void }
        def initialize(organization_id:, date:, external_product_id:, external_id: nil, description: nil, product: nil, product_id: nil, product_name: nil, product_description: nil, original_currency: nil, destination_currency: nil, converted_amount: nil, converted_taxable_amount: nil, converted_tax_amount_imported: nil, converted_tax_amount_calculated: nil, converted_total_discount: nil, converted_subtotal: nil, tax_exemption: nil, tax_items: nil, discount_builder: nil, quantity: 1.0, amount: 0.00, tax_amount_imported: 0.00, tax_rate_imported: 0.00, tax_amount_calculated: 0.00, tax_rate_calculated: 0.00, taxable_amount: 0.00, exempt: false)
          @organization_id = organization_id
          @date = date
          @external_product_id = external_product_id
          @external_id = external_id
          @description = description
          @product = product
          @product_id = product_id
          @product_name = product_name
          @product_description = product_description
          @original_currency = original_currency
          @destination_currency = destination_currency
          @converted_amount = converted_amount
          @converted_taxable_amount = converted_taxable_amount
          @converted_tax_amount_imported = converted_tax_amount_imported
          @converted_tax_amount_calculated = converted_tax_amount_calculated
          @converted_total_discount = converted_total_discount
          @converted_subtotal = converted_subtotal
          @tax_exemption = tax_exemption
          @tax_items = tax_items
          @discount_builder = discount_builder
          @quantity = quantity
          @amount = amount
          @tax_amount_imported = tax_amount_imported
          @tax_rate_imported = tax_rate_imported
          @tax_amount_calculated = tax_amount_calculated
          @tax_rate_calculated = tax_rate_calculated
          @taxable_amount = taxable_amount
          @exempt = exempt
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @organization_id == other.organization_id
          return false unless @date == other.date
          return false unless @external_product_id == other.external_product_id
          return false unless @external_id == other.external_id
          return false unless @description == other.description
          return false unless @product == other.product
          return false unless @product_id == other.product_id
          return false unless @product_name == other.product_name
          return false unless @product_description == other.product_description
          return false unless @original_currency == other.original_currency
          return false unless @destination_currency == other.destination_currency
          return false unless @converted_amount == other.converted_amount
          return false unless @converted_taxable_amount == other.converted_taxable_amount
          return false unless @converted_tax_amount_imported == other.converted_tax_amount_imported
          return false unless @converted_tax_amount_calculated == other.converted_tax_amount_calculated
          return false unless @converted_total_discount == other.converted_total_discount
          return false unless @converted_subtotal == other.converted_subtotal
          return false unless @tax_exemption == other.tax_exemption
          return false unless @tax_items == other.tax_items
          return false unless @discount_builder == other.discount_builder
          return false unless @quantity == other.quantity
          return false unless @amount == other.amount
          return false unless @tax_amount_imported == other.tax_amount_imported
          return false unless @tax_rate_imported == other.tax_rate_imported
          return false unless @tax_amount_calculated == other.tax_amount_calculated
          return false unless @tax_rate_calculated == other.tax_rate_calculated
          return false unless @taxable_amount == other.taxable_amount
          return false unless @exempt == other.exempt
          true
        end
      end
    end
  end
end
