# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class TransactionAddressReadOutput
        extend T::Sig
        include Crystalline::MetadataFields


        field :type, Models::Shared::AddressType, { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('type'), required: true, 'decoder': Utils.enum_from_string(Models::Shared::AddressType, false) } }
        # Phone number associated with the address.
        field :phone, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('phone') } }
        # Primary street address.
        field :street_1, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('street_1') } }
        # Additional street address details, such as an apartment or suite number.
        field :street_2, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('street_2') } }
        # City where the customer resides.
        field :city, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('city') } }
        # County or district of the customer.
        field :county, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('county') } }
        # State or province of the customer.
        field :state, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('state') } }
        # ZIP or Postal code of the customer.
        field :postal_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('postal_code') } }

        field :country, Crystalline::Nilable.new(Models::Shared::CountryCodeEnum), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('country'), 'decoder': Utils.enum_from_string(Models::Shared::CountryCodeEnum, true) } }
        # Complete address string of the customer, which can be used as an alternative to individual fields.
        field :full_address, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('full_address') } }

        field :status, Crystalline::Nilable.new(Models::Shared::AddressStatus), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Shared::AddressStatus, true) } }
        # Unique identifier of the address being updated.
        field :id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('id') } }
        # ID of the transaction associated with the address.
        field :transaction_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('transaction_id') } }
        # ID of the connection associated with the address.
        field :connection_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('connection_id') } }

        sig { params(type: Models::Shared::AddressType, phone: T.nilable(::String), street_1: T.nilable(::String), street_2: T.nilable(::String), city: T.nilable(::String), county: T.nilable(::String), state: T.nilable(::String), postal_code: T.nilable(::String), country: T.nilable(Models::Shared::CountryCodeEnum), full_address: T.nilable(::String), status: T.nilable(Models::Shared::AddressStatus), id: T.nilable(::String), transaction_id: T.nilable(::String), connection_id: T.nilable(::String)).void }
        def initialize(type:, phone: nil, street_1: nil, street_2: nil, city: nil, county: nil, state: nil, postal_code: nil, country: nil, full_address: nil, status: nil, id: nil, transaction_id: nil, connection_id: nil)
          @type = type
          @phone = phone
          @street_1 = street_1
          @street_2 = street_2
          @city = city
          @county = county
          @state = state
          @postal_code = postal_code
          @country = country
          @full_address = full_address
          @status = status
          @id = id
          @transaction_id = transaction_id
          @connection_id = connection_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @phone == other.phone
          return false unless @street_1 == other.street_1
          return false unless @street_2 == other.street_2
          return false unless @city == other.city
          return false unless @county == other.county
          return false unless @state == other.state
          return false unless @postal_code == other.postal_code
          return false unless @country == other.country
          return false unless @full_address == other.full_address
          return false unless @status == other.status
          return false unless @id == other.id
          return false unless @transaction_id == other.transaction_id
          return false unless @connection_id == other.connection_id
          true
        end
      end
    end
  end
end
