# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared

      class TransactionDirectionEnum < T::Enum
        enums do
          SALE = new('SALE')
          PURCHASE = new('PURCHASE')
        end
      end
    end
  end
end
