# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Shared
    

      class TransactionTypeEnum < T::Enum


        enums do
          SALE = new('SALE')
          FULL_CREDIT_NOTE = new('FULL_CREDIT_NOTE')
          PARTIAL_CREDIT_NOTE = new('PARTIAL_CREDIT_NOTE')
          TAX_REFUND = new('TAX_REFUND')
          ARCHIVE = new('ARCHIVE')
        end
      end
    end
  end
end
