# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module KintsugiSDK
  autoload :OpenApiSDK, 'kintsugi_sdk/openapisdk'
  autoload :AddressValidation, 'kintsugi_sdk/addressvalidation'
  autoload :Customers, 'kintsugi_sdk/customers'
  autoload :Exemptions, 'kintsugi_sdk/exemptions'
  autoload :Nexus, 'kintsugi_sdk/nexus'
  autoload :Products, 'kintsugi_sdk/products'
  autoload :Transactions, 'kintsugi_sdk/transactions'
  autoload :TaxEstimation, 'kintsugi_sdk/taxestimation'
  module Models
    autoload :Shared, 'kintsugi_sdk/models/shared'
    autoload :Ops, 'kintsugi_sdk/models/ops'
    autoload :Errors, 'kintsugi_sdk/models/errors'
    autoload :Callbacks, 'kintsugi_sdk/models/callbacks'
  end
end

require_relative 'kintsugi_sdk/utils/utils'
require_relative 'kintsugi_sdk/utils/request_bodies'
require_relative 'kintsugi_sdk/utils/query_params'
require_relative 'kintsugi_sdk/utils/forms'
require_relative 'kintsugi_sdk/utils/headers'
require_relative 'kintsugi_sdk/utils/url'
require_relative 'kintsugi_sdk/utils/security'
require_relative 'crystalline'
require_relative 'kintsugi_sdk/sdkconfiguration'
