# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  autoload :SDK, 'open_api_sdk/sdk'
  autoload :AddressValidation, 'open_api_sdk/addressvalidation'
  autoload :Customers, 'open_api_sdk/customers'
  autoload :Exemptions, 'open_api_sdk/exemptions'
  autoload :Nexus, 'open_api_sdk/nexus'
  autoload :Products, 'open_api_sdk/products'
  autoload :Transactions, 'open_api_sdk/transactions'
  autoload :TaxEstimation, 'open_api_sdk/taxestimation'
  module Models
    autoload :Components, 'open_api_sdk/models/components'
    autoload :Operations, 'open_api_sdk/models/operations'
    autoload :Errors, 'open_api_sdk/models/errors'
    autoload :Callbacks, 'open_api_sdk/models/callbacks'
  end
end

require_relative 'open_api_sdk/utils/utils'
require_relative 'open_api_sdk/utils/request_bodies'
require_relative 'open_api_sdk/utils/query_params'
require_relative 'open_api_sdk/utils/forms'
require_relative 'open_api_sdk/utils/headers'
require_relative 'open_api_sdk/utils/url'
require_relative 'open_api_sdk/utils/security'
require_relative 'crystalline'
require_relative 'open_api_sdk/sdkconfiguration'
