# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module KintsugiSDK
  module Models
    module Errors
    

      class HTTPValidationError
        extend T::Sig
        include Crystalline::MetadataFields


        field :detail, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::ValidationError)), { 'format_json': { 'letter_case': ::KintsugiSDK::Utils.field_name('detail') } }

        sig { params(detail: T.nilable(T::Array[Models::Shared::ValidationError])).void }
        def initialize(detail: nil)
          @detail = detail
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @detail == other.detail
          true
        end
      end
    end
  end
end
