# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module KintsugiSDK
  module Models
    module Errors
      autoload :APIError, 'kintsugi_sdk/models/errors/apierror.rb'
      autoload :ErrorResponse, 'kintsugi_sdk/models/errors/errorresponse.rb'
      autoload :HTTPValidationError, 'kintsugi_sdk/models/errors/httpvalidationerror.rb'
      autoload :BackendSrcAddressValidationResponsesValidationErrorResponse, 'kintsugi_sdk/models/errors/backend_src_address_validation_responses_validationerrorresponse.rb'
      autoload :BackendSrcCustomersResponsesValidationErrorResponse, 'kintsugi_sdk/models/errors/backend_src_customers_responses_validationerrorresponse.rb'
      autoload :BackendSrcExemptionsResponsesValidationErrorResponse, 'kintsugi_sdk/models/errors/backend_src_exemptions_responses_validationerrorresponse.rb'
      autoload :BackendSrcProductsResponsesValidationErrorResponse, 'kintsugi_sdk/models/errors/backend_src_products_responses_validationerrorresponse.rb'
      autoload :BackendSrcTaxEstimationResponsesValidationErrorResponse, 'kintsugi_sdk/models/errors/backend_src_tax_estimation_responses_validationerrorresponse.rb'
      autoload :BackendSrcTransactionsResponsesValidationErrorResponse, 'kintsugi_sdk/models/errors/backend_src_transactions_responses_validationerrorresponse.rb'
    end
  end
end
