# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class AddressStatus < T::Enum
        enums do
          UNVERIFIED = new('UNVERIFIED')
          INVALID = new('INVALID')
          PARTIALLY_VERIFIED = new('PARTIALLY_VERIFIED')
          VERIFIED = new('VERIFIED')
          UNVERIFIABLE = new('UNVERIFIABLE')
          BLANK = new('BLANK')
        end
      end
    end
  end
end
