# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    
      # Pre-calculated tax rate for the item, if provided by the external system.
      class CreditNoteItemCreateUpdateTaxRateImported
        extend T::Sig
        include Crystalline::MetadataFields


        
        def initialize; end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, CreditNoteItemCreateUpdateTaxRateImported)
          true
        end
      end
    end
  end
end
