# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    
      # Total portion of the credit note amount subject to taxation.
      class CreditNoteCreateTaxableAmount
        extend T::Sig
        include Crystalline::MetadataFields


        
        def initialize; end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, CreditNoteCreateTaxableAmount)
          true
        end
      end
    end
  end
end
