# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class DiscountBuilder
        extend T::Sig
        include Crystalline::MetadataFields


        field :applied_to, Models::Components::AppliedTo, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('applied_to'), required: true, 'decoder': Utils.enum_from_string(Models::Components::AppliedTo, false) } }

        field :discount_amount, T.nilable(T.any(::Float, ::String)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('discount_amount') } }

        field :external_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('external_id') } }

        sig { params(applied_to: Models::Components::AppliedTo, discount_amount: T.nilable(T.any(::Float, ::String)), external_id: T.nilable(::String)).void }
        def initialize(applied_to:, discount_amount: nil, external_id: nil)
          @applied_to = applied_to
          @discount_amount = discount_amount
          @external_id = external_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, DiscountBuilder)
          return false unless @applied_to == other.applied_to
          return false unless @discount_amount == other.discount_amount
          return false unless @external_id == other.external_id
          true
        end
      end
    end
  end
end
