# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class ExemptionStatus < T::Enum
        enums do
          ACTIVE = new('ACTIVE')
          INACTIVE = new('INACTIVE')
          EXPIRED = new('EXPIRED')
          DEACTIVATED = new('DEACTIVATED')
          ARCHIVED = new('ARCHIVED')
        end
      end
    end
  end
end
