# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class ExemptionCreate
        extend T::Sig
        include Crystalline::MetadataFields


        field :exemption_type, Models::Components::ExemptionType, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('exemption_type'), required: true, 'decoder': Utils.enum_from_string(Models::Components::ExemptionType, false) } }
        # Start date for the exemption validity period (YYYY-MM-DD format)
        field :start_date, ::Date, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('start_date'), required: true, 'decoder': Utils.date_from_iso_format(false) } }
        # Unique identifier for the customer associated with the exemption
        field :customer_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer_id'), required: true } }
        # Federal Employer Identification Number
        field :fein, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('FEIN'), required: true } }
        # Sales tax ID for the exemption
        field :sales_tax_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sales_tax_id'), required: true } }

        field :status, Models::Components::ExemptionStatus, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Components::ExemptionStatus, false) } }
        # The jurisdiction identifier for the exemption
        field :jurisdiction, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('jurisdiction') } }
        # Country code in ISO 3166-1 alpha-2 format (e.g., 'US')
        field :country_code, T.nilable(Models::Components::CountryCodeEnum), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('country_code'), 'decoder': Utils.enum_from_string(Models::Components::CountryCodeEnum, true) } }
        # End date for the exemption validity period (YYYY-MM-DD format)
        field :end_date, T.nilable(::Date), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('end_date'), 'decoder': Utils.date_from_iso_format(true) } }
        # Unique identifier for the transaction, if applicable
        field :transaction_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('transaction_id') } }
        # Indicates whether the exemption is for a reseller
        field :reseller, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('reseller') } }

        sig { params(exemption_type: Models::Components::ExemptionType, start_date: ::Date, customer_id: ::String, fein: ::String, sales_tax_id: ::String, status: Models::Components::ExemptionStatus, jurisdiction: T.nilable(::String), country_code: T.nilable(Models::Components::CountryCodeEnum), end_date: T.nilable(::Date), transaction_id: T.nilable(::String), reseller: T.nilable(T::Boolean)).void }
        def initialize(exemption_type:, start_date:, customer_id:, fein:, sales_tax_id:, status:, jurisdiction: nil, country_code: nil, end_date: nil, transaction_id: nil, reseller: false)
          @exemption_type = exemption_type
          @start_date = start_date
          @customer_id = customer_id
          @fein = fein
          @sales_tax_id = sales_tax_id
          @status = status
          @jurisdiction = jurisdiction
          @country_code = country_code
          @end_date = end_date
          @transaction_id = transaction_id
          @reseller = reseller
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, ExemptionCreate)
          return false unless @exemption_type == other.exemption_type
          return false unless @start_date == other.start_date
          return false unless @customer_id == other.customer_id
          return false unless @fein == other.fein
          return false unless @sales_tax_id == other.sales_tax_id
          return false unless @status == other.status
          return false unless @jurisdiction == other.jurisdiction
          return false unless @country_code == other.country_code
          return false unless @end_date == other.end_date
          return false unless @transaction_id == other.transaction_id
          return false unless @reseller == other.reseller
          true
        end
      end
    end
  end
end
