# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class NexusStatusEnum < T::Enum
        enums do
          NEEDS_RERUN = new('NEEDS_RERUN')
          UP_TO_DATE = new('UP_TO_DATE')
          NOT_READY = new('NOT_READY')
        end
      end
    end
  end
end
