# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class NexusTypeEnum < T::Enum
        enums do
          CANADA_FEDERAL = new('CANADA_FEDERAL')
          EU_AGGREGATOR = new('EU_AGGREGATOR')
          STATE = new('STATE')
          EU_MEMBER_STATE = new('EU_MEMBER_STATE')
        end
      end
    end
  end
end
