# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class ProductRead
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }

        field :external_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('external_id'), required: true } }

        field :code, T.any(Models::Components::ProductCodeEnum, ::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('code'), required: true } }

        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name'), required: true } }

        field :status, Models::Components::ProductStatusEnum, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Components::ProductStatusEnum, false) } }

        field :product_category, T.any(Models::Components::ProductCategoryEnum, ::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_category'), required: true } }

        field :product_subcategory, T.any(Models::Components::ProductSubCategoryEnum, ::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_subcategory'), required: true } }

        field :tax_exempt, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tax_exempt'), required: true } }

        field :source, Models::Components::SourceEnum, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('source'), required: true, 'decoder': Utils.enum_from_string(Models::Components::SourceEnum, false) } }

        field :sku, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sku'), required: true } }

        field :description, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description'), required: true } }

        field :connection_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('connection_id'), required: true } }

        field :classification_failed, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('classification_failed'), required: true } }

        sig { params(id: ::String, external_id: ::String, code: T.any(Models::Components::ProductCodeEnum, ::String), name: ::String, status: Models::Components::ProductStatusEnum, product_category: T.any(Models::Components::ProductCategoryEnum, ::String), product_subcategory: T.any(Models::Components::ProductSubCategoryEnum, ::String), tax_exempt: T::Boolean, source: Models::Components::SourceEnum, sku: T.nilable(T::Array[::String]), description: T.nilable(::String), connection_id: T.nilable(::String), classification_failed: T.nilable(T::Boolean)).void }
        def initialize(id:, external_id:, code:, name:, status:, product_category:, product_subcategory:, tax_exempt:, source:, sku: nil, description: nil, connection_id: nil, classification_failed: nil)
          @id = id
          @external_id = external_id
          @code = code
          @name = name
          @status = status
          @product_category = product_category
          @product_subcategory = product_subcategory
          @tax_exempt = tax_exempt
          @source = source
          @sku = sku
          @description = description
          @connection_id = connection_id
          @classification_failed = classification_failed
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, ProductRead)
          return false unless @id == other.id
          return false unless @external_id == other.external_id
          return false unless @code == other.code
          return false unless @name == other.name
          return false unless @status == other.status
          return false unless @product_category == other.product_category
          return false unless @product_subcategory == other.product_subcategory
          return false unless @tax_exempt == other.tax_exempt
          return false unless @source == other.source
          return false unless @sku == other.sku
          return false unless @description == other.description
          return false unless @connection_id == other.connection_id
          return false unless @classification_failed == other.classification_failed
          true
        end
      end
    end
  end
end
