# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class ProductCreateManual
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique external identifier for the product.
        field :external_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('external_id'), required: true } }
        # The name of the product.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name'), required: true } }
        # The high-level category of the product.
        field :product_category, T.any(Models::Components::ProductCategoryEnum, ::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_category'), required: true } }
        # The subcategory of the product.
        field :product_subcategory, T.any(Models::Components::ProductSubCategoryEnum, ::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('product_subcategory'), required: true } }
        # Specifies whether the product is tax-exempt.
        field :tax_exempt, T::Boolean, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tax_exempt'), required: true } }

        field :status, T.nilable(Models::Components::ProductStatusEnum), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status'), 'decoder': Utils.enum_from_string(Models::Components::ProductStatusEnum, true) } }

        field :source, T.nilable(Models::Components::SourceEnum), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('source'), 'decoder': Utils.enum_from_string(Models::Components::SourceEnum, true) } }
        # A description of the product.
        field :description, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }

        sig { params(external_id: ::String, name: ::String, product_category: T.any(Models::Components::ProductCategoryEnum, ::String), product_subcategory: T.any(Models::Components::ProductSubCategoryEnum, ::String), tax_exempt: T::Boolean, status: T.nilable(Models::Components::ProductStatusEnum), source: T.nilable(Models::Components::SourceEnum), description: T.nilable(::String)).void }
        def initialize(external_id:, name:, product_category:, product_subcategory:, tax_exempt:, status: nil, source: nil, description: nil)
          @external_id = external_id
          @name = name
          @product_category = product_category
          @product_subcategory = product_subcategory
          @tax_exempt = tax_exempt
          @status = status
          @source = source
          @description = description
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, ProductCreateManual)
          return false unless @external_id == other.external_id
          return false unless @name == other.name
          return false unless @product_category == other.product_category
          return false unless @product_subcategory == other.product_subcategory
          return false unless @tax_exempt == other.tax_exempt
          return false unless @status == other.status
          return false unless @source == other.source
          return false unless @description == other.description
          true
        end
      end
    end
  end
end
