# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class ProductStatusEnum < T::Enum
        enums do
          APPROVED = new('APPROVED')
          PARTIALLY_APPROVED = new('PARTIALLY_APPROVED')
          PENDING = new('PENDING')
        end
      end
    end
  end
end
