# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    
      # Status - Current state of the credit note in its lifecycle.
      class Status < T::Enum
        enums do
          PENDING = new('PENDING')
          CANCELLED = new('CANCELLED')
          COMMITTED = new('COMMITTED')
        end
      end
    end
  end
end
