# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class StatusEnum < T::Enum
        enums do
          ACTIVE = new('ACTIVE')
          ARCHIVED = new('ARCHIVED')
        end
      end
    end
  end
end
