# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class TaxItemBuilder
        extend T::Sig
        include Crystalline::MetadataFields


        field :rate, T.any(::Float, ::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('rate'), required: true } }

        field :amount, T.any(::Float, ::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('amount'), required: true } }
        # Deprecated: use `jurisdiction_type` instead
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name'), required: true } }

        field :type, T.nilable(Models::Components::TaxItemTypeEnum), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type'), 'decoder': Utils.enum_from_string(Models::Components::TaxItemTypeEnum, true) } }

        field :organization_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('organization_id'), required: true } }
        # The rule ID of the tax item
        field :rule_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('rule_id') } }

        field :converted_amount, T.nilable(T.any(::Float, ::String)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('converted_amount') } }

        field :currency, T.nilable(Models::Components::CurrencyEnum), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('currency'), 'decoder': Utils.enum_from_string(Models::Components::CurrencyEnum, true) } }

        field :destination_currency, T.nilable(Models::Components::CurrencyEnum), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('destination_currency'), 'decoder': Utils.enum_from_string(Models::Components::CurrencyEnum, true) } }

        field :external_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('external_id') } }

        field :jurisdiction_type, T.nilable(Models::Components::JurisdictionType), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('jurisdiction_type'), 'decoder': Utils.enum_from_string(Models::Components::JurisdictionType, true) } }

        field :jurisdiction_name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('jurisdiction_name') } }

        sig { params(rate: T.any(::Float, ::String), amount: T.any(::Float, ::String), name: ::String, type: T.nilable(Models::Components::TaxItemTypeEnum), organization_id: T.nilable(::String), rule_id: T.nilable(::String), converted_amount: T.nilable(T.any(::Float, ::String)), currency: T.nilable(Models::Components::CurrencyEnum), destination_currency: T.nilable(Models::Components::CurrencyEnum), external_id: T.nilable(::String), jurisdiction_type: T.nilable(Models::Components::JurisdictionType), jurisdiction_name: T.nilable(::String)).void }
        def initialize(rate:, amount:, name:, type: nil, organization_id: nil, rule_id: '0000', converted_amount: nil, currency: nil, destination_currency: nil, external_id: nil, jurisdiction_type: nil, jurisdiction_name: nil)
          @rate = rate
          @amount = amount
          @name = name
          @type = type
          @organization_id = organization_id
          @rule_id = rule_id
          @converted_amount = converted_amount
          @currency = currency
          @destination_currency = destination_currency
          @external_id = external_id
          @jurisdiction_type = jurisdiction_type
          @jurisdiction_name = jurisdiction_name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, TaxItemBuilder)
          return false unless @rate == other.rate
          return false unless @amount == other.amount
          return false unless @name == other.name
          return false unless @type == other.type
          return false unless @organization_id == other.organization_id
          return false unless @rule_id == other.rule_id
          return false unless @converted_amount == other.converted_amount
          return false unless @currency == other.currency
          return false unless @destination_currency == other.destination_currency
          return false unless @external_id == other.external_id
          return false unless @jurisdiction_type == other.jurisdiction_type
          return false unless @jurisdiction_name == other.jurisdiction_name
          true
        end
      end
    end
  end
end
