# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    
      # Request model for tax estimation, including all fields from TransactionEstimateBase
      # and an additional field to simulate nexus being met.
      class TransactionEstimateRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The date of the transaction in ISO 8601 format (e.g., 2025-01-25T12:00:00Z).
        field :date, ::DateTime, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('date'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }
        # Unique identifier of this transaction in the source system.
        field :external_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('external_id'), required: true } }

        field :currency, Models::Components::CurrencyEnum, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('currency'), required: true, 'decoder': Utils.enum_from_string(Models::Components::CurrencyEnum, false) } }
        # List of addresses related to the transaction. At least one BILL_TO or SHIP_TO address must be provided. The address will be validated during estimation, and the transaction may be rejected if the address does not pass validation. The SHIP_TO will be preferred to use for determining tax liability. **Deprecated:** Use of `address.status` in estimate api is ignored and will be removed in the future status will be considered UNVERIFIED by default and always validated
        field :addresses, T::Array[Models::Components::TransactionEstimateRequestAddress], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('addresses'), required: true } }
        # List of items involved in the transaction.
        field :transaction_items, T::Array[Models::Components::TransactionItemEstimateBase], { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('transaction_items'), required: true } }
        # Total amount of the transaction.
        field :total_amount, T.nilable(T.any(::Float, ::String)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('total_amount') } }
        # An optional description of the transaction.
        field :description, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }
        # While currently not used, it may be used in the future to determine taxability. The source of the transaction (e.g., OTHER).
        # 
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :source, T.nilable(Models::Components::SourceEnum), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('source'), 'decoder': Utils.enum_from_string(Models::Components::SourceEnum, true) } }
        # Indicates if the transaction involves a marketplace.
        field :marketplace, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('marketplace') } }
        # Details about the customer. If the customer is not found, it will be ignored.
        field :customer, T.nilable(Models::Components::CustomerBaseInput), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customer') } }
        # If True, assumes active registration is met for tax estimation.
        field :simulate_active_registration, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('simulate_active_registration') } }
        # Use simulate_active_registration instead.
        #         This field will be removed in future releases.
        # 
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :simulate_nexus_met, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('simulate_nexus_met') } }

        sig { params(date: ::DateTime, external_id: ::String, currency: Models::Components::CurrencyEnum, addresses: T::Array[Models::Components::TransactionEstimateRequestAddress], transaction_items: T::Array[Models::Components::TransactionItemEstimateBase], total_amount: T.nilable(T.any(::Float, ::String)), description: T.nilable(::String), source: T.nilable(Models::Components::SourceEnum), marketplace: T.nilable(T::Boolean), customer: T.nilable(Models::Components::CustomerBaseInput), simulate_active_registration: T.nilable(T::Boolean), simulate_nexus_met: T.nilable(T::Boolean)).void }
        def initialize(date:, external_id:, currency:, addresses:, transaction_items:, total_amount: nil, description: nil, source: nil, marketplace: nil, customer: nil, simulate_active_registration: nil, simulate_nexus_met: nil)
          @date = date
          @external_id = external_id
          @currency = currency
          @addresses = addresses
          @transaction_items = transaction_items
          @total_amount = total_amount
          @description = description
          @source = source
          @marketplace = marketplace
          @customer = customer
          @simulate_active_registration = simulate_active_registration
          @simulate_nexus_met = simulate_nexus_met
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, TransactionEstimateRequest)
          return false unless @date == other.date
          return false unless @external_id == other.external_id
          return false unless @currency == other.currency
          return false unless @addresses == other.addresses
          return false unless @transaction_items == other.transaction_items
          return false unless @total_amount == other.total_amount
          return false unless @description == other.description
          return false unless @source == other.source
          return false unless @marketplace == other.marketplace
          return false unless @customer == other.customer
          return false unless @simulate_active_registration == other.simulate_active_registration
          return false unless @simulate_nexus_met == other.simulate_nexus_met
          true
        end
      end
    end
  end
end
