# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    
      # TransactionExemptStatusEnum - Based on transaction item exempt status.
      # NOT EXEMPT: None of the items are NOT EXEMPT
      # PARTIALLY EXEMPT: At least some of the items are NOT EXEMPT
      # FULLY_EXEMPT: All items sold in the transaction are EXEMPT
      class TransactionExemptStatusEnum < T::Enum
        enums do
          NOT_EXEMPT = new('NOT_EXEMPT')
          PARTIALLY_EXEMPT = new('PARTIALLY_EXEMPT')
          FULLY_EXEMPT = new('FULLY_EXEMPT')
        end
      end
    end
  end
end
