# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class TreatmentEnum < T::Enum
        enums do
          INCLUDED = new('INCLUDED')
          EXCLUDED = new('EXCLUDED')
          DEPENDS = new('DEPENDS')
          YES_SALES_NO_TRANSACTIONS = new('YES_SALES_NO_TRANSACTIONS')
        end
      end
    end
  end
end
