# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CreateCreditNoteByTransactionIdV1TransactionsOriginalTransactionIdCreditNotesPostRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :original_transaction_id, ::String, { 'path_param': { 'field_name': 'original_transaction_id', 'style': 'simple', 'explode': false } }

        field :credit_note_create, Models::Components::CreditNoteCreate, { 'request': { 'media_type': 'application/json' } }
        # The unique identifier for the organization making the request
        field :x_organization_id, T.nilable(::String), { 'header': { 'field_name': 'x-organization-id', 'style': 'simple', 'explode': false } }

        sig { params(original_transaction_id: ::String, credit_note_create: Models::Components::CreditNoteCreate, x_organization_id: T.nilable(::String)).void }
        def initialize(original_transaction_id:, credit_note_create:, x_organization_id: nil)
          @original_transaction_id = original_transaction_id
          @credit_note_create = credit_note_create
          @x_organization_id = x_organization_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, CreateCreditNoteByTransactionIdV1TransactionsOriginalTransactionIdCreditNotesPostRequest)
          return false unless @original_transaction_id == other.original_transaction_id
          return false unless @credit_note_create == other.credit_note_create
          return false unless @x_organization_id == other.x_organization_id
          true
        end
      end
    end
  end
end
