# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class CreateTransactionV1TransactionsPostRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :transaction_public_request, Models::Components::TransactionPublicRequest, { 'request': { 'media_type': 'application/json' } }
        # The unique identifier for the organization making the request
        field :x_organization_id, T.nilable(::String), { 'header': { 'field_name': 'x-organization-id', 'style': 'simple', 'explode': false } }

        sig { params(transaction_public_request: Models::Components::TransactionPublicRequest, x_organization_id: T.nilable(::String)).void }
        def initialize(transaction_public_request:, x_organization_id: nil)
          @transaction_public_request = transaction_public_request
          @x_organization_id = x_organization_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, CreateTransactionV1TransactionsPostRequest)
          return false unless @transaction_public_request == other.transaction_public_request
          return false unless @x_organization_id == other.x_organization_id
          true
        end
      end
    end
  end
end
