# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class EstimateTaxV1TaxEstimatePostRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :transaction_estimate_request, Models::Components::TransactionEstimateRequest, { 'request': { 'media_type': 'application/json' } }
        # **Deprecated:** Use `simulate_active_registration` in the request body instead.
        # 
        # @deprecated  true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :simulate_nexus_met, T.nilable(T::Boolean), { 'query_param': { 'field_name': 'simulate_nexus_met', 'style': 'form', 'explode': true } }
        # The unique identifier for the organization making the request
        field :x_organization_id, T.nilable(::String), { 'header': { 'field_name': 'x-organization-id', 'style': 'simple', 'explode': false } }

        sig { params(transaction_estimate_request: Models::Components::TransactionEstimateRequest, simulate_nexus_met: T.nilable(T::Boolean), x_organization_id: T.nilable(::String)).void }
        def initialize(transaction_estimate_request:, simulate_nexus_met: nil, x_organization_id: nil)
          @transaction_estimate_request = transaction_estimate_request
          @simulate_nexus_met = simulate_nexus_met
          @x_organization_id = x_organization_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, EstimateTaxV1TaxEstimatePostRequest)
          return false unless @transaction_estimate_request == other.transaction_estimate_request
          return false unless @simulate_nexus_met == other.simulate_nexus_met
          return false unless @x_organization_id == other.x_organization_id
          true
        end
      end
    end
  end
end
