# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetAttachmentsForExemptionV1ExemptionsExemptionIdAttachmentsGetRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier for the exemption
        #         whose attachments are being retrieved.
        field :exemption_id, ::String, { 'path_param': { 'field_name': 'exemption_id', 'style': 'simple', 'explode': false } }
        # The unique identifier for the organization making the request
        field :x_organization_id, T.nilable(::String), { 'header': { 'field_name': 'x-organization-id', 'style': 'simple', 'explode': false } }

        sig { params(exemption_id: ::String, x_organization_id: T.nilable(::String)).void }
        def initialize(exemption_id:, x_organization_id: nil)
          @exemption_id = exemption_id
          @x_organization_id = x_organization_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, GetAttachmentsForExemptionV1ExemptionsExemptionIdAttachmentsGetRequest)
          return false unless @exemption_id == other.exemption_id
          return false unless @x_organization_id == other.x_organization_id
          true
        end
      end
    end
  end
end
