# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetTransactionsV1TransactionsGetRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique identifier for the organization making the request
        field :x_organization_id, T.nilable(::String), { 'header': { 'field_name': 'x-organization-id', 'style': 'simple', 'explode': false } }
        # Filter transactions by state code.
        field :state_code, T.nilable(::String), { 'query_param': { 'field_name': 'state_code', 'style': 'form', 'explode': true } }
        # Filter by transaction type (e.g., SALE, FULL_CREDIT_NOTE,
        #         PARTIAL_CREDIT_NOTE, ARCHIVE etc.).
        field :transaction_type, T.nilable(::String), { 'query_param': { 'field_name': 'transaction_type', 'style': 'form', 'explode': true } }
        # Filter transactions based on the source.
        field :transaction_source, T.nilable(::String), { 'query_param': { 'field_name': 'transaction_source', 'style': 'form', 'explode': true } }
        # Search for transactions using a general query
        #         (e.g., order ID, customer name).
        field :search_query, T.nilable(::String), { 'query_param': { 'field_name': 'search_query', 'style': 'form', 'explode': true } }
        # Filter transactions by country code
        #         (ISO 3166-1 alpha-2 format, e.g., US).
        field :country, T.nilable(T::Array[T.any(Models::Components::CountryCodeEnum, ::String)]), { 'query_param': { 'field_name': 'country', 'style': 'form', 'explode': true } }
        # Filter by full state name (e.g., California).
        field :state, T.nilable(::String), { 'query_param': { 'field_name': 'state', 'style': 'form', 'explode': true } }
        # Filter by address status (e.g., UNVERIFIED, INVALID,
        #         PARTIALLY_VERIFIED, VERIFIED, UNVERIFIABLE).
        field :address_status_in, T.nilable(::String), { 'query_param': { 'field_name': 'address_status__in', 'style': 'form', 'explode': true } }
        # Filter by transaction status (e.g., PENDING, COMMITTED,
        #         CANCELLED, FULLY_REFUNDED, PARTIALLY_REFUNDED, ARCHIVED).
        field :status, T.nilable(Models::Components::TransactionStatusEnum), { 'query_param': { 'field_name': 'status', 'style': 'form', 'explode': true } }
        # Retrieve transactions linked to a specific filing ID.
        field :filing_id, T.nilable(::String), { 'query_param': { 'field_name': 'filing_id', 'style': 'form', 'explode': true } }
        # Sort results based on specified fields.
        #         Prefix with - for descending order (e.g., -date for newest first).
        field :order_by, T.nilable(::String), { 'query_param': { 'field_name': 'order_by', 'style': 'form', 'explode': true } }
        # Retrieve transactions with a date
        #         greater than or equal to (YYYY-MM-DD).
        field :date_gte, T.nilable(::Date), { 'query_param': { 'field_name': 'date__gte', 'style': 'form', 'explode': true } }
        # Retrieve transactions with a date
        #         less than or equal to (YYYY-MM-DD).
        field :date_lte, T.nilable(::Date), { 'query_param': { 'field_name': 'date__lte', 'style': 'form', 'explode': true } }
        # Filter transactions based on processing status.
        #         Multiple values can be passed as a comma-separated list.
        field :processing_status_in, T.nilable(::String), { 'query_param': { 'field_name': 'processing_status__in', 'style': 'form', 'explode': true } }
        # Filter transactions by marketplace (e.g., AMAZON, EBAY).
        field :marketplace, T.nilable(T::Boolean), { 'query_param': { 'field_name': 'marketplace', 'style': 'form', 'explode': true } }
        # Page number
        field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # Page size
        field :size, T.nilable(::Integer), { 'query_param': { 'field_name': 'size', 'style': 'form', 'explode': true } }

        sig { params(x_organization_id: T.nilable(::String), state_code: T.nilable(::String), transaction_type: T.nilable(::String), transaction_source: T.nilable(::String), search_query: T.nilable(::String), country: T.nilable(T::Array[T.any(Models::Components::CountryCodeEnum, ::String)]), state: T.nilable(::String), address_status_in: T.nilable(::String), status: T.nilable(Models::Components::TransactionStatusEnum), filing_id: T.nilable(::String), order_by: T.nilable(::String), date_gte: T.nilable(::Date), date_lte: T.nilable(::Date), processing_status_in: T.nilable(::String), marketplace: T.nilable(T::Boolean), page: T.nilable(::Integer), size: T.nilable(::Integer)).void }
        def initialize(x_organization_id: nil, state_code: nil, transaction_type: nil, transaction_source: nil, search_query: nil, country: nil, state: nil, address_status_in: nil, status: nil, filing_id: nil, order_by: nil, date_gte: nil, date_lte: nil, processing_status_in: nil, marketplace: nil, page: 1, size: 50)
          @x_organization_id = x_organization_id
          @state_code = state_code
          @transaction_type = transaction_type
          @transaction_source = transaction_source
          @search_query = search_query
          @country = country
          @state = state
          @address_status_in = address_status_in
          @status = status
          @filing_id = filing_id
          @order_by = order_by
          @date_gte = date_gte
          @date_lte = date_lte
          @processing_status_in = processing_status_in
          @marketplace = marketplace
          @page = page
          @size = size
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, GetTransactionsV1TransactionsGetRequest)
          return false unless @x_organization_id == other.x_organization_id
          return false unless @state_code == other.state_code
          return false unless @transaction_type == other.transaction_type
          return false unless @transaction_source == other.transaction_source
          return false unless @search_query == other.search_query
          return false unless @country == other.country
          return false unless @state == other.state
          return false unless @address_status_in == other.address_status_in
          return false unless @status == other.status
          return false unless @filing_id == other.filing_id
          return false unless @order_by == other.order_by
          return false unless @date_gte == other.date_gte
          return false unless @date_lte == other.date_lte
          return false unless @processing_status_in == other.processing_status_in
          return false unless @marketplace == other.marketplace
          return false unless @page == other.page
          return false unless @size == other.size
          true
        end
      end
    end
  end
end
