# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :customer_id, ::String, { 'path_param': { 'field_name': 'customer_id', 'style': 'simple', 'explode': false } }
        # The unique identifier for the organization making the request
        field :x_organization_id, T.nilable(::String), { 'header': { 'field_name': 'x-organization-id', 'style': 'simple', 'explode': false } }

        sig { params(customer_id: ::String, x_organization_id: T.nilable(::String)).void }
        def initialize(customer_id:, x_organization_id: nil)
          @customer_id = customer_id
          @x_organization_id = x_organization_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, GetTransactionsByCustomerIdV1CustomersCustomerIdTransactionsGetRequest)
          return false unless @customer_id == other.customer_id
          return false unless @x_organization_id == other.x_organization_id
          true
        end
      end
    end
  end
end
