# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class SearchV1AddressValidationSearchPostResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # Address found successfully
        field :response_200_search_v1_address_validation_search_post, T.nilable(T::Array[Models::Components::AddressSearchResponse])

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, response_200_search_v1_address_validation_search_post: T.nilable(T::Array[Models::Components::AddressSearchResponse])).void }
        def initialize(content_type:, status_code:, raw_response:, response_200_search_v1_address_validation_search_post: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @response_200_search_v1_address_validation_search_post = response_200_search_v1_address_validation_search_post
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, SearchV1AddressValidationSearchPostResponse)
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @response_200_search_v1_address_validation_search_post == other.response_200_search_v1_address_validation_search_post
          true
        end
      end
    end
  end
end
