# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UpdateTransactionV1TransactionsTransactionIdPutRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :transaction_id, ::String, { 'path_param': { 'field_name': 'transaction_id', 'style': 'simple', 'explode': false } }

        field :transaction_update, Models::Components::TransactionUpdate, { 'request': { 'media_type': 'application/json' } }
        # The unique identifier for the organization making the request
        field :x_organization_id, T.nilable(::String), { 'header': { 'field_name': 'x-organization-id', 'style': 'simple', 'explode': false } }

        sig { params(transaction_id: ::String, transaction_update: Models::Components::TransactionUpdate, x_organization_id: T.nilable(::String)).void }
        def initialize(transaction_id:, transaction_update:, x_organization_id: nil)
          @transaction_id = transaction_id
          @transaction_update = transaction_update
          @x_organization_id = x_organization_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          T.cast(other, UpdateTransactionV1TransactionsTransactionIdPutRequest)
          return false unless @transaction_id == other.transaction_id
          return false unless @transaction_update == other.transaction_update
          return false unless @x_organization_id == other.x_organization_id
          true
        end
      end
    end
  end
end
